apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-local-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  
  accessModes:
    - ReadWriteOnce
  
  #For dynamic volume creation
  storageClassName: local-storage

  #For already created volume which storage class is not required
  #volumeName: ebs-static-pv    # <-- binds to that PV by name

